module.exports = Object.freeze({
    ACTIVE: 'ACTIVE',
    BLOCK: 'BLOCKED',
    DELETE: 'DELETE' ,
    APPROVED:"APPROVED",
    ACCEPTED:"ACCEPTED",
    PENDING: 'PENDING',
    REJECT:"REJECT",
    RESOLVED:"RESOLVED",
    COMPLETED:"COMPLETED",
    IN_PROGRESS:'IN PROGRESS',
    CONFIRMED:"CONFIRMED",
    COMMENTED:"COMMENTED",
    DELIVER:"DELIVER"
    
})